# Generated by Django 4.0.4 on 2022-05-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ano', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(default=0)),
                ('etcs', models.IntegerField(default=0)),
                ('anoLetivo', models.IntegerField(default=0)),
                ('topicos', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
    ]
