# Generated by Django 4.0.4 on 2022-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_blog_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='linguagem',
            field=models.ManyToManyField(related_name='linguagens', to='portfolio.linguagem'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='professorPraticas',
            field=models.ManyToManyField(related_name='cadeiras', to='portfolio.professor'),
        ),
    ]
