# Generated by Django 4.0.4 on 2022-05-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_cadeira_linguagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
    ]
