# Generated by Django 4.0.4 on 2022-05-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_blog_imagem_remove_blog_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
    ]
